sudo: required

language: scala

scala:
  - 2.11.7

services:
  - docker

env:
  global:
  - secure: CbxqEQVOaEuRCGxQNx0mlLG68Qhx9d7ihilEfSb2/THyknD6LhAqOrC0AKYWXUiYlUbaQKw20WfV/6rb3vvj6sEEignzbK5vKvICZ/LZAVBspvkQo6R7kQAYwE+w2Q3ZHc6VBItoqMHVVppyHUb7YvJc/pCx1LdldPLmyBXt9MEggEPJcqsZfZjIEmYaXflXiRXwWeTpTCKRzQfE01jI7RUqKBhGTsnjIzZYT6iZMyW12UpAC8JRrtqHJXWJzE0alvZf+yhHpwhPKcz11xf5PYuwHeaYHo54kjcql9t9K3CNdZwSkRPP/m/OAv++FRAR9kF/yza7e80gJPryVJtZoZfJnxiSwMJurIaPIWn5VppP22IxnWtQfOpTPR1Mmh72DOs0pG2BEdcFDVcSBbT7X6+9u5s4NCzexoB5vIDy0OhBE6a7dlpPZf12OtrV2FlahPtpr1Wlv7lNnWRvch68iVShishi6jNPb/OhR34dBLXmbfx+jMXWBvyggEsbNeLmFjJN11LLgf46GLq04RPgpUWAhibUrK7AIm/CpHV44xhrZERd9x1JSbRGxTYPg1MWdDdm9kT3Z+WOawhTdyGkkEGwC0hpsHnR3HkjjBGVe3yx3/WRol+MTI1GBw+VTqXBe4SPFLo63cFpIPsqaWnnA5q+kRyJfXAcjBTkl9PXjZo=
  - secure: qd5Q8aL2dToMYe6F9ECMs96Y0ReB8GETv9Gn0+okvZs96Hxun0Z6JDlV6sX0J5nTYkd1QA9Ol+SOom6LNmhPn9zwEb4pxeDjD3CgK9g354Cqksjd5flqxZpEXlPQRzng07tn+IhjUmMRdbLAiMwggD6O17t7SleocozFJab46rTkmOjAWrKj2cKCcvMZoqxjWSpMWCSmFqV8MpE28vTuJLf45xcqhtPWGC55LybJDfZhDMIPf1lrQHSOufKo4kRtxQeMaMpJx3MOp3piVATMByZpKZ/RgeSg+iHTCElccY3vyV4h//Dykx7wKtlOUK5VPLsI8VvTF98vZX79mXXAhFFbCkHCRvo+uCTDXBepnLy1uV4JoRW2HgTAzjC9MkIgk+qrn8LA2l/leiYJlJtIUpvrYh+kYBN8LU1c5OL+R2siGaevQWPXM53k9W7ycZ2CHcKc59LpEF/GIDbEVSvciW/gQSWWT/scXKOWOblwhupf1IRLNDyDLJozVkTGkIznamXy/0mOyX0uTv/KvibxFITHthGRqm+x8VDBzgQJT65EVS17JxVzxbZtN1vJJ2Ms7UOQAV08M8CiSEEBmvjJJ8EHenWe9v98a+a9nJbzf07I14NU8nrgQtp/P7MUYbJrlv17p9iDQ2p49KFep4OGmt1/6eUON3TkXYFiVGsYkMA=
  - secure: GTCr8/YV/MPxAA/fZSDooZkS+Xqc2p8NedcWkULOvINxOVJ2wAwl709u/P4LbXBINPTctZYf8wr8g5j0t/GloS6yvWpkGwp8w9Lfl2cvKViLPLs4jnRaeuCQbAn7an7VkVyBxb2Zu+Kp0vhA1HyN1jmQVv1DiWLHdp9165K5L+OJ+72GUqkSzs9DM+4WvMHBBv6aeBj8lgdviNjPOJQTwgUWfJVAPVEC7O+zPl+htVClIFyCzDhGRkf6smFqgA4e1uiERvL5VnRkV3JvRM1M8qFXfQpkwrTNsd1LpLwdkSkjVWEVnSEtkKHy2tX77xVzRdjLcXAavcmNLI9J3b3C06ev3bmdziKh4Fb5Ryo9qZKOEXBY+mWhRyKXP3N7Y4CWfJnmZC8OJD7TTkBWnpcz0XL3aYizzPPUM4srKxu9Jwcjkm5ejzVXq61opIWeW1QXboycQ9nVkipe8VWJn8FuDAV+TE6nSDVdlOF0rCB7L/fl1u3L0wHddGgQBODuHrVf4hMbdAq6xOh4DuRAkQxZ7ZnU8w1hvrowoTrIamazL2SzEE0Cqr30d3hHJYLasL8ws732dRDVpxJKUYbHGRQiALkY/uRLwqpwf0erMzv8qE637ilduKxgqmGcbszZJlt4+nm/lLtoH9vWYXatymFQL07s8AkxpXAgELCTB4iakik=

script:
  - sbt test docker:publishLocal

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_LOGIN" -p="$DOCKER_PASS";
    docker push impactua/sender-app;
    fi
